In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('consolidated.tsv', sep='\t')
df['N nodes'] = [1, 2, 4, 8, 16]
df

,Unnamed: 0,filename,height,width,length,time_steps,mpi_tasks,mpi_x,mpi_y,mpi_z,...,avg_temp_start,iteration_time_s,mpi_time_s,compute_time_s,avg_temp_end,nodes,mpi_fraction,compute_fraction,speedup,N nodes
0,0,slurm-scalability-19461872.out,960,960,960,300,128,8,4,4,...,63.836582,31.527600,7.256294,14.665611,63.835413,NaN,0.230157,0.465167,1.000000,1
1,1,slurm-n2-19461883.out,960,960,960,300,256,8,8,4,...,63.836582,17.289084,5.196818,5.907539,63.835413,2.0,0.300584,0.341692,1.823555,2
2,2,slurm-n4-19461895.out,960,960,960,300,512,8,8,8,...,63.836582,9.935390,3.523513,2.245864,63.835413,4.0,0.354643,0.226047,3.173262,4
3,3,slurm-n8-19461896.out,960,960,960,300,1024,16,8,8,...,63.836582,5.586569,1.604494,1.013162,63.835413,8.0,0.287206,0.181357,5.643464,8
4,4,slurm-n16-19461898.out,960,960,960,300,2048,16,16,8,...,63.836582,3.207301,0.391788,0.458115,63.835413,16.0,0.122155,0.142835,9.829947,16

In [3]:
nodes = df['N nodes']
runtime = df['iteration_time_s']
t1 = runtime.iloc[0]

power_per_node_w = 600
price_per_node_hour = 4

results = pd.DataFrame({
    'Nodes': nodes,
    'Runtime (s)': runtime,
})
results['Resource cost (Node-s)'] = results['Nodes'] * results['Runtime (s)']
results['Speedup'] = t1 / results['Runtime (s)']
results['Parallel efficiency (%)'] = 100 * results['Speedup'] / results['Nodes']
results['Electricity cost (Wh)'] = results['Resource cost (Node-s)'] * power_per_node_w / 3600
results['Monetary cost (\u20ac)'] = results['Resource cost (Node-s)'] / 3600 * price_per_node_hour

results

,Nodes,Runtime (s),Resource cost (Node-s),Speedup,Parallel efficiency (%),Electricity cost (Wh),Monetary cost (€)
0,1,31.527600,31.527600,1.000000,100.000000,5.254600,0.035031
1,2,17.289084,34.578168,1.823555,91.177763,5.763028,0.038420
2,4,9.935390,39.741560,3.173262,79.331561,6.623593,0.044157
3,8,5.586569,44.692552,5.643464,70.543298,7.448759,0.049658
4,16,3.207301,51.316816,9.829947,61.437171,8.552803,0.057019